# Generated by Django 3.2.7 on 2021-09-20 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Susbcriber', 'verbose_name_plural': 'Subscribers'},
        ),
    ]
